/* Standalone select checks; no running backend or deployment data required. */
const assert = require("node:assert/strict");
const path = require("node:path");
const { chromium } = require(process.env.STUDIO_PLAYWRIGHT || "playwright");
const assets = path.resolve(__dirname, "../pages/image-studio");

(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    for (const { width, height, theme } of [{ width: 1440, height: 1000, theme: "light" }, { width: 360, height: 800, theme: "dark" }]) {
      const page = await browser.newPage({ viewport: { width, height }, hasTouch: width < 600 });
      page.setDefaultTimeout(6000);
      const errors = [];
      page.on("pageerror", (error) => errors.push(error.message));
      await page.setContent(`<!doctype html><html data-theme="${theme}"><head></head><body style="padding:16px"><form id="testForm"><label class="field" style="max-width:320px">模型<select id="model" required><option value="">请选择</option><option value="alpha">Alpha</option><option value="blocked" disabled>Blocked</option><option value="beta">Beta</option><option value="gamma">Gamma</option></select></label><button id="after" type="button">Next</button></form><fieldset id="disabledGroup"><label class="field">方式<select id="mode"><option value="one">One</option><option value="two">Two</option></select></label></fieldset><div id="dynamic"></div></body></html>`);
      await page.addStyleTag({ path: path.join(assets, "app.css") });
      await page.addStyleTag({ path: path.join(assets, "library.css") });
      await page.addStyleTag({ path: path.join(assets, "select.css") });
      await page.addScriptTag({ path: path.join(assets, "vendor/lucide/icons.js") });
      await page.addScriptTag({ path: path.join(assets, "select.js") });
      const trigger = page.locator('.studio-select-trigger[data-select-id="model"]');
      await trigger.waitFor();
      await page.evaluate(() => { window.changed = 0; document.getElementById("model").addEventListener("change", () => window.changed++); });
      await trigger.click();
      assert.equal(await page.locator('.studio-select-menu [role="option"]').count(), 5);
      await page.keyboard.press("ArrowDown");
      await page.keyboard.press("ArrowDown");
      await page.keyboard.press("Enter");
      assert.equal(await page.locator("#model").inputValue(), "beta");
      assert.equal(await page.evaluate(() => window.changed), 1);
      assert.equal(await trigger.getAttribute("aria-expanded"), "false");
      await trigger.press("Space");
      await page.keyboard.press("End");
      await page.keyboard.press("Escape");
      assert.equal(await page.locator("#model").inputValue(), "beta");
      assert.equal(await trigger.evaluate((element) => document.activeElement === element), true);
      await trigger.click();
      await page.keyboard.press("a");
      await page.keyboard.press("Enter");
      assert.equal(await page.locator("#model").inputValue(), "alpha");
      await page.evaluate(() => { const select = document.getElementById("model"); select.value = "gamma"; window.ImageStudioSelect.refresh(select); });
      assert.equal(await trigger.locator(".studio-select-value").textContent(), "Gamma");
      assert.equal(await page.evaluate(() => window.changed), 2);
      await trigger.click();
      await page.mouse.click(width - 4, height / 2);
      assert.equal(await page.locator(".studio-select-menu").count(), 0);
      await trigger.click();
      await page.evaluate(() => { document.getElementById("model").innerHTML = '<option value="new">New</option>'; });
      await page.locator('.studio-select-option-label').filter({ hasText: "New" }).waitFor();
      assert.equal(await page.locator('.studio-select-menu [role="option"]').count(), 1);
      await page.evaluate(() => { document.getElementById("model").classList.add("is-hidden"); });
      await trigger.waitFor({ state: "hidden" });
      assert.equal(await page.locator(".studio-select-menu").count(), 0);
      await page.evaluate(() => { document.getElementById("model").classList.remove("is-hidden"); document.getElementById("disabledGroup").disabled = true; });
      await page.locator('.studio-select-trigger[data-select-id="mode"]:disabled').waitFor();
      await page.evaluate(() => { document.getElementById("dynamic").innerHTML = '<label class="field">动态<select id="added"><option value="a">A</option><option value="b">B</option></select></label>'; });
      await page.locator('.studio-select-trigger[data-select-id="added"]').waitFor();
      await page.evaluate(() => { document.getElementById("dynamic").innerHTML = ''; });
      await page.evaluate(() => { const select = document.getElementById("model"); select.innerHTML = '<option value="">请选择</option><option value="a">A</option>'; window.ImageStudioSelect.refresh(); select.reportValidity(); });
      assert.equal(await trigger.getAttribute("aria-invalid"), "true");
      assert.equal(await trigger.evaluate((element) => document.activeElement === element), true);
      await page.evaluate(() => { document.getElementById("testForm").style.cssText = "position:fixed;bottom:12px;right:8px;width:260px"; });
      await trigger.click();
      const box = await page.locator(".studio-select-menu").boundingBox();
      assert.ok(box.x >= 7 && box.y >= 7 && box.x + box.width <= width - 7 && box.y + box.height <= height - 7, JSON.stringify(box));
      assert.equal(await page.locator(".studio-select-menu").getAttribute("data-placement"), "above");
      await page.evaluate(() => { document.getElementById("testForm").remove(); });
      await page.locator(".studio-select-menu").waitFor({ state: "detached" });
      await page.evaluate(() => {
        document.getElementById("dynamic").innerHTML = '<label class="field">新增模型<input id="customModel" list="suggestions" /><datalist id="suggestions"><option value="nai-v45">NovelAI V4.5</option><option value="nai-v5">NovelAI V5</option><option value="gpt-image">GPT Image</option></datalist></label>';
        window.customInputEvents = 0; window.customChangeEvents = 0;
        document.getElementById("customModel").addEventListener("input", () => window.customInputEvents++);
        document.getElementById("customModel").addEventListener("change", () => window.customChangeEvents++);
      });
      const editable = page.locator("#customModel");
      await page.locator('#customModel[data-studio-datalist="suggestions"]').waitFor();
      assert.equal(await editable.getAttribute("list"), null, "native datalist popup must be removed");
      await editable.fill("nai");
      assert.equal(await page.locator('.studio-select-menu [role="option"]').count(), 2);
      await page.keyboard.press("ArrowDown"); await page.keyboard.press("Enter");
      assert.equal(await editable.inputValue(), "nai-v45");
      assert.equal(await page.locator(".studio-select-menu").count(), 0);
      assert.equal(await page.evaluate(() => window.customInputEvents), 2);
      assert.equal(await page.evaluate(() => window.customChangeEvents), 1);
      await editable.fill("custom-new-model");
      assert.equal(await page.locator('.studio-select-menu [role="option"]').count(), 0);
      await page.keyboard.press("Escape");
      assert.equal(await editable.inputValue(), "custom-new-model");
      await page.locator(".studio-combobox-toggle").click();
      assert.equal(await page.locator('.studio-select-menu [role="option"]').count(), 3);
      await page.evaluate(() => { document.getElementById("suggestions").innerHTML = '<option value="future-model">Future Model</option>'; });
      await page.locator(".studio-select-option-label").filter({ hasText: "Future Model" }).waitFor();
      await page.keyboard.press("Escape");
      await page.evaluate(() => { document.getElementById("customModel").value = "manual-value"; window.ImageStudioSelect.refresh(); });
      assert.equal(await editable.inputValue(), "manual-value");
      await page.evaluate(() => {
        const select = document.createElement("select"); select.id = "replaced"; select.innerHTML = '<option value="a">A</option><option value="b">B</option>'; document.body.appendChild(select);
        window.replacedChangeEvents = 0;
        select.addEventListener("input", () => { select.closest(".studio-select").remove(); });
        select.addEventListener("change", () => window.replacedChangeEvents++);
      });
      await page.locator('.studio-select-trigger[data-select-id="replaced"]').click();
      await page.keyboard.press("ArrowDown"); await page.keyboard.press("Enter");
      assert.equal(await page.evaluate(() => window.replacedChangeEvents), 0, "detached source must not get a second change event");
      assert.deepEqual(errors, []);
      await page.close();
      console.log(`${width}px ${theme}: select and editable combobox keyboard, events, dynamic updates, disabled, hidden, validation, placement passed`);
    }
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
