/* Standalone select checks; no running backend or deployment data required. */
const assert = require("node:assert/strict");
const path = require("node:path");
const { chromium } = require(process.env.STUDIO_PLAYWRIGHT || "playwright");
const assets = path.resolve(__dirname, "../../pages/image-studio");

(async () => {
  const browser = await chromium.launch({ headless: true });
  try {
    for (const { width, height, theme } of [{ width: 1440, height: 1000, theme: "light" }, { width: 360, height: 800, theme: "dark" }]) {
      const page = await browser.newPage({ viewport: { width, height }, hasTouch: width < 600 });
      page.setDefaultTimeout(6000);
      const errors = [];
      page.on("pageerror", (error) => errors.push(error.message));
      await page.setContent(`<!doctype html><html data-theme="${theme}"><head></head><body style="padding:16px"><form id="testForm"><label class="field" style="max-width:320px">模型<select id="model" required><option value="">请选择</option><option value="alpha">Alpha</option><option value="blocked" disabled>Blocked</option><option value="beta">Beta</option><option value="gamma">Gamma</option></select></label><button id="after" type="button">Next</button></form><fieldset id="disabledGroup"><label class="field">方式<select id="mode"><option value="one">One</option><option value="two">Two</option></select></label></fieldset><div id="dynamic"></div></body></html>`);
      await page.addStyleTag({ path: path.join(assets, "app.css") });
      await page.addStyleTag({ path: path.join(assets, "library.css") });
      await page.addStyleTag({ path: path.join(assets, "select.css") });
      await page.addScriptTag({ path: path.join(assets, "vendor/lucide/icons.js") });
      await page.addScriptTag({ path: path.join(assets, "select.js") });
      const trigger = page.locator('.studio-select-trigger[data-select-id="model"]');
      await trigger.waitFor();
      assert.equal(await trigger.getAttribute("data-tooltip"), "请选择", "implicit hints only reveal the displayed value when clipped");
      assert.equal(await trigger.getAttribute("data-tooltip-overflow"), ".studio-select-value");
      await page.evaluate(() => { const select = document.getElementById("model"); select.dataset.tooltip = "选择用于生成图片的模型"; window.ImageStudioSelect.refresh(select); });
      assert.equal(await trigger.getAttribute("data-tooltip"), "选择用于生成图片的模型", "meaningful explicit descriptions survive select enhancement");
      await page.evaluate(() => { const select = document.getElementById("model"); delete select.dataset.tooltip; window.ImageStudioSelect.refresh(select); });
      await page.evaluate(() => { window.changed = 0; document.getElementById("model").addEventListener("change", () => window.changed++); });
      await trigger.click();
      assert.equal(await page.locator('.studio-select-menu [role="option"]').count(), 5);
      await page.keyboard.press("ArrowDown");
      await page.keyboard.press("ArrowDown");
      await page.keyboard.press("Enter");
      assert.equal(await page.locator("#model").inputValue(), "beta");
      assert.equal(await page.evaluate(() => window.changed), 1);
      assert.equal(await trigger.getAttribute("aria-expanded"), "false");
      await trigger.press("Space");
      await page.keyboard.press("End");
      await page.keyboard.press("Escape");
      assert.equal(await page.locator("#model").inputValue(), "beta");
      assert.equal(await trigger.evaluate((element) => document.activeElement === element), true);
      await trigger.click();
      await page.keyboard.press("a");
      await page.keyboard.press("Enter");
      assert.equal(await page.locator("#model").inputValue(), "alpha");
      await page.evaluate(() => { const select = document.getElementById("model"); select.value = "gamma"; window.ImageStudioSelect.refresh(select); });
      assert.equal(await trigger.locator(".studio-select-value").textContent(), "Gamma");
      assert.equal(await trigger.getAttribute("data-tooltip"), "Gamma", "selection changes must refresh the uncluttered overflow hint");
      assert.equal(await page.evaluate(() => window.changed), 2);
      await trigger.click();
      await page.mouse.click(width - 4, height / 2);
      assert.equal(await page.locator(".studio-select-menu").count(), 0);
      await trigger.click();
      await page.evaluate(() => { document.getElementById("model").innerHTML = '<option value="new">New</option>'; });
      await page.locator('.studio-select-option-label').filter({ hasText: "New" }).waitFor();
      assert.equal(await page.locator('.studio-select-menu [role="option"]').count(), 1);
      await page.evaluate(() => { document.getElementById("model").classList.add("is-hidden"); });
      await trigger.waitFor({ state: "hidden" });
      assert.equal(await page.locator(".studio-select-menu").count(), 0);
      await page.evaluate(() => { document.getElementById("model").classList.remove("is-hidden"); document.getElementById("disabledGroup").disabled = true; });
      await page.locator('.studio-select-trigger[data-select-id="mode"]:disabled').waitFor();
      await page.evaluate(() => { document.getElementById("dynamic").innerHTML = '<label class="field">动态<select id="added"><option value="a">A</option><option value="b">B</option></select></label>'; });
      await page.locator('.studio-select-trigger[data-select-id="added"]').waitFor();
      await page.evaluate(() => { document.getElementById("dynamic").innerHTML = ''; });
      await page.evaluate(() => { const select = document.getElementById("model"); select.innerHTML = '<option value="">请选择</option><option value="a">A</option>'; window.ImageStudioSelect.refresh(); select.reportValidity(); });
      assert.equal(await trigger.getAttribute("aria-invalid"), "true");
      assert.equal(await trigger.evaluate((element) => document.activeElement === element), true);
      await page.evaluate(() => { document.getElementById("testForm").style.cssText = "position:fixed;bottom:12px;right:8px;width:260px"; });
      await trigger.click();
      const box = await page.locator(".studio-select-menu").boundingBox();
      assert.ok(box.x >= 7 && box.y >= 7 && box.x + box.width <= width - 7 && box.y + box.height <= height - 7, JSON.stringify(box));
      assert.equal(await page.locator(".studio-select-menu").getAttribute("data-placement"), "above");
      await page.evaluate(() => { document.getElementById("testForm").remove(); });
      await page.locator(".studio-select-menu").waitFor({ state: "detached" });
      await page.evaluate(() => {
        document.getElementById("dynamic").innerHTML = '<label class="field">新增模型<input id="customModel" list="suggestions" /><datalist id="suggestions"><option value="nai-v45">NovelAI V4.5</option><option value="nai-v5">NovelAI V5</option><option value="gpt-image">GPT Image</option></datalist></label>';
        window.customInputEvents = 0; window.customChangeEvents = 0;
        document.getElementById("customModel").addEventListener("input", () => window.customInputEvents++);
        document.getElementById("customModel").addEventListener("change", () => window.customChangeEvents++);
      });
      const editable = page.locator("#customModel");
      await page.locator('#customModel[data-studio-datalist="suggestions"]').waitFor();
      assert.equal(await editable.getAttribute("list"), null, "native datalist popup must be removed");
      assert.equal(await page.locator(".studio-combobox-toggle").getAttribute("data-tooltip"), null, "the suggestion arrow should not repeat its accessible action label");
      assert.ok(await page.locator(".studio-combobox-toggle").getAttribute("aria-label"));
      await editable.fill("nai");
      assert.equal(await page.locator('.studio-select-menu [role="option"]').count(), 2);
      await page.keyboard.press("ArrowDown"); await page.keyboard.press("Enter");
      assert.equal(await editable.inputValue(), "nai-v45");
      assert.equal(await page.locator(".studio-select-menu").count(), 0);
      assert.equal(await page.evaluate(() => window.customInputEvents), 2);
      assert.equal(await page.evaluate(() => window.customChangeEvents), 1);
      await editable.fill("custom-new-model");
      assert.equal(await page.locator('.studio-select-menu [role="option"]').count(), 0);
      await page.keyboard.press("Escape");
      assert.equal(await editable.inputValue(), "custom-new-model");
      await page.locator(".studio-combobox-toggle").click();
      assert.equal(await page.locator('.studio-select-menu [role="option"]').count(), 3);
      await page.evaluate(() => { document.getElementById("suggestions").innerHTML = '<option value="future-model">Future Model</option>'; });
      await page.locator(".studio-select-option-label").filter({ hasText: "Future Model" }).waitFor();
      await page.keyboard.press("Escape");
      await page.evaluate(() => { document.getElementById("customModel").value = "manual-value"; window.ImageStudioSelect.refresh(); });
      assert.equal(await editable.inputValue(), "manual-value");
      await page.evaluate(() => {
        const select = document.createElement("select"); select.id = "replaced"; select.innerHTML = '<option value="a">A</option><option value="b">B</option>'; document.body.appendChild(select);
        window.replacedChangeEvents = 0;
        select.addEventListener("input", () => { select.closest(".studio-select").remove(); });
        select.addEventListener("change", () => window.replacedChangeEvents++);
      });
      await page.locator('.studio-select-trigger[data-select-id="replaced"]').click();
      await page.keyboard.press("ArrowDown"); await page.keyboard.press("Enter");
      assert.equal(await page.evaluate(() => window.replacedChangeEvents), 0, "detached source must not get a second change event");
      await page.evaluate(() => {
        const form = document.createElement("form"); form.id = "multiForm";
        form.innerHTML = '<label class="field" style="max-width:320px">服务商<select id="multi" multiple data-all-label="全部服务商"><option value="" selected>未指定服务商</option><option value="alpha" selected>Alpha</option><option value="beta" selected>Beta</option></select></label><button id="afterMulti" type="button">Next</button>';
        document.body.appendChild(form);
        window.multiEvents = [];
        for (const type of ["input", "change"]) document.getElementById("multi").addEventListener(type, () => window.multiEvents.push({ type, values: Array.from(document.getElementById("multi").selectedOptions, (option) => option.value) }));
      });
      const multi = page.locator('.studio-select-trigger[data-select-id="multi"]');
      const multiValue = multi.locator(".studio-select-value");
      const multiMenu = page.locator('.studio-select-menu[data-select-id="multi"]');
      const selectedValues = () => page.locator("#multi").evaluate((select) => Array.from(select.selectedOptions, (option) => option.value));
      await multi.waitFor();
      assert.equal(await multiValue.textContent(), "全部服务商");
      assert.equal(await multi.getAttribute("data-tooltip"), "全部服务商", "all-selected summaries do not implicitly enumerate every option");
      assert.equal(await multi.getAttribute("data-tooltip-overflow"), ".studio-select-value");
      assert.deepEqual(await selectedValues(), ["", "alpha", "beta"]);
      await multi.click();
      assert.equal(await multiMenu.locator('[role="listbox"]').getAttribute("aria-multiselectable"), "true");
      assert.equal(await multiMenu.locator('[role="option"][aria-selected="true"]').count(), 3);
      assert.equal(await multiMenu.locator('[data-select-action="all"]').isDisabled(), true);
      await multiMenu.locator('[data-option-index="2"]').click();
      assert.deepEqual(await selectedValues(), ["", "alpha"]);
      assert.equal(await multiValue.textContent(), "已选 2 项");
      assert.equal(await multi.getAttribute("data-tooltip"), "已选 2 项", "partial-selection summaries do not implicitly enumerate selections");
      assert.equal(await multi.getAttribute("aria-expanded"), "true");
      assert.equal(await multiMenu.locator('[role="option"][aria-selected="true"]').count(), 2);
      await multiMenu.locator('[data-option-index="0"]').click();
      assert.deepEqual(await selectedValues(), ["alpha"], "empty string is a selectable provider, not an all sentinel");
      assert.equal(await multiValue.textContent(), "Alpha");
      await page.keyboard.press("End");
      assert.deepEqual(await selectedValues(), ["alpha"], "arrow navigation must not change selection");
      await page.keyboard.press("Space");
      assert.deepEqual(await selectedValues(), ["alpha", "beta"]);
      await page.keyboard.press("Home"); await page.keyboard.press("Space");
      assert.equal(await multiValue.textContent(), "全部服务商");
      await page.keyboard.press("Control+a");
      assert.equal(await page.evaluate(() => window.multiEvents.length), 8, "selecting all again is a no-op");
      await multiMenu.locator('[data-select-action="clear"]').click();
      assert.deepEqual(await selectedValues(), []);
      assert.equal(await multiValue.textContent(), "未选择");
      assert.equal(await multiMenu.locator('[data-select-action="clear"]').isDisabled(), true);
      await multiMenu.locator('[data-select-action="all"]').click();
      assert.deepEqual(await selectedValues(), ["", "alpha", "beta"]);
      await page.keyboard.press("Control+Shift+a");
      assert.deepEqual(await selectedValues(), []);
      await page.keyboard.press("Control+a");
      assert.equal(await multiValue.textContent(), "全部服务商");
      await page.evaluate(() => { const select = document.getElementById("multi"); select.options[2].selected = false; window.ImageStudioSelect.refresh(select); });
      assert.equal(await multiValue.textContent(), "已选 2 项", "refresh must detect selection changes after the first selected option");
      assert.equal(await multiMenu.locator('[data-option-index="2"]').getAttribute("aria-selected"), "false");
      const multiEvents = await page.evaluate(() => window.multiEvents);
      assert.equal(multiEvents.length, 16, "each user change emits one input/change pair and refresh emits neither");
      for (let index = 0; index < multiEvents.length; index += 2) {
        assert.equal(multiEvents[index].type, "input"); assert.equal(multiEvents[index + 1].type, "change");
        assert.deepEqual(multiEvents[index].values, multiEvents[index + 1].values);
      }
      await page.keyboard.press("Escape");
      assert.equal(await multiMenu.count(), 0);
      assert.equal(await multi.evaluate((element) => document.activeElement === element), true);
      await multi.press("Space"); await page.keyboard.press("Tab");
      assert.equal(await multiMenu.count(), 0);
      assert.equal(await page.locator("#afterMulti").evaluate((element) => document.activeElement === element), true);
      await page.evaluate(() => document.getElementById("multiForm").reset());
      await page.waitForFunction(() => document.querySelector('.studio-select-trigger[data-select-id="multi"] .studio-select-value').textContent === "全部服务商");
      await page.evaluate(() => document.getElementById("multi").dataset.allLabel = "全部选项");
      await page.waitForFunction(() => document.querySelector('.studio-select-trigger[data-select-id="multi"] .studio-select-value').textContent === "全部选项");
      await multi.click();
      const multiBox = await multiMenu.boundingBox();
      assert.ok(multiBox.x >= 7 && multiBox.y >= 7 && multiBox.x + multiBox.width <= width - 7 && multiBox.y + multiBox.height <= height - 7, JSON.stringify(multiBox));
      assert.equal(await multiMenu.locator('.studio-select-mark').first().evaluate((element) => getComputedStyle(element).visibility), "visible");
      await page.evaluate(() => {
        const select = document.getElementById("multi");
        select.options[1].disabled = true; select.options[2].hidden = true;
      });
      await multiMenu.locator('[data-option-index="1"][aria-disabled="true"]').waitFor();
      assert.equal(await multiMenu.locator('[role="option"]').count(), 2);
      await multiMenu.locator('[data-select-action="clear"]').click();
      assert.deepEqual(await selectedValues(), ["alpha", "beta"], "bulk operations preserve disabled and hidden selections");
      await multiMenu.locator('[data-option-index="1"]').click({ force: true });
      assert.deepEqual(await selectedValues(), ["alpha", "beta"]);
      await page.keyboard.press("Home"); await page.keyboard.press("ArrowDown"); await page.keyboard.press("Space");
      assert.deepEqual(await selectedValues(), ["", "alpha", "beta"], "keyboard navigation skips disabled and hidden options");
      await page.evaluate(() => { const select = document.getElementById("multi"); select.innerHTML = '<option value="new" selected>New</option><option value="later">Later</option>'; });
      await multiMenu.locator('.studio-select-option-label').filter({ hasText: "New" }).waitFor();
      assert.equal(await multiValue.textContent(), "New");
      await page.evaluate(() => { const select = document.getElementById("multi"); select.addEventListener("input", () => select.closest(".studio-select").remove(), { once: true }); });
      const eventsBeforeRemoval = await page.evaluate(() => window.multiEvents.length);
      await multiMenu.locator('[data-option-index="1"]').click();
      assert.equal(await page.evaluate(() => window.multiEvents.length), eventsBeforeRemoval + 1, "detached multiple source must not get a second change event");
      await multiMenu.waitFor({ state: "detached" });
      assert.deepEqual(errors, []);
      await page.close();
      console.log(`${width}px ${theme}: single/multiple select and editable combobox keyboard, events, bulk selection, dynamic updates, disabled, hidden, validation, placement passed`);
    }
  } finally { await browser.close(); }
})().catch((error) => { console.error(error); process.exitCode = 1; });
